# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
- task: S3Upload@1
  inputs:
    awsCredentials: 'AWS-USer-1'
    regionName: 'ap-south-1'
    bucketName: 'newbuck'
    globExpressions: '**'
    createBucket: true
    keyManagement: 'awsManaged'
    encryptionAlgorithm: 'AES256'
    globExpressions: '**'
    createBucket: true

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
