# Hello , changes done
#aasdasdsad
#asdjbksbvndbfjkds
# Repo: chetagra/TemplateRepo
# File: azure-pipeline.yml

name: cicd_ci

trigger:
  branches:
    include:
      - master

stages:
- stage: CI_Checks
  jobs:
  - job:
    displayName: yamllint_checks
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        python -m pip install --upgrade pip
        pip install yamllint
        yamllint -d "{extends: relaxed, rules: {line-length: {max: 200}, new-line-at-end-of-file: disable, new-lines: disable}}" .
      displayName: 'YAML Lint Checks'

    - task: S3Upload@1
      inputs:
        awsCredentials: 'AWS-USer-1'
        regionName: 'ap-southeast-2'
        bucketName: 'NewBuck'
        globExpressions: '**'
        createBucket: true
        keyManagement: 'awsManaged'
        encryptionAlgorithm: 'AES256'
